# Matrix

In [1]:
import numpy as np

In [3]:
a = np.matrix("1, 2, 3, 4; 5, 6, 7, 8; 9, 10, 11, 12")

In [4]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Matrix Properties

In [13]:
a.shape

(3, 4)

In [11]:
a.shape[0]

3

In [10]:
a.shape[1]

4

In [14]:
a.size

12

## Modifying Matrix

In [16]:
# np.insert(matrix, object or position, values, axis)

np.insert(a, 2, 20, 0)

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [20, 20, 20, 20],
        [ 9, 10, 11, 12]])

#### Inserting a new Matrix

In [20]:
col_new = np.matrix("20, 21, 22")
col_new

matrix([[20, 21, 22]])

In [23]:
row_new = np.matrix('30, 31, 32, 33')
row_new

matrix([[30, 31, 32, 33]])

In [21]:
#adding column wise
np.insert(a, 0, col_new, axis = 1)

matrix([[20,  1,  2,  3,  4],
        [21,  5,  6,  7,  8],
        [22,  9, 10, 11, 12]])

In [24]:
#adding row wise
np.insert(a, 0, row_new, 0)

matrix([[30, 31, 32, 33],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

### Updating a Matrix

In [26]:
b = np.insert(a, 0, row_new, 0)
b

matrix([[30, 31, 32, 33],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [27]:
#Replacing element [1, 1] position
b[1, 1] = 100
b

matrix([[ 30,  31,  32,  33],
        [  1, 100,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]])

In [29]:
# Accessing Elements of a Matrix using Index
b

matrix([[ 30,  31,  32,  33],
        [  1, 100,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]])

In [31]:
# Index row 1 and 2 columns
print(b[1, :2])

[[  1 100]]
