# Matrix

In [1]:
import numpy as np

In [3]:
a = np.matrix("1, 2, 3, 4; 5, 6, 7, 8; 9, 10, 11, 12")

In [4]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Matrix Properties

In [13]:
a.shape

(3, 4)

In [11]:
a.shape[0]

3

In [10]:
a.shape[1]

4

In [14]:
a.size

12

## Modifying Matrix

In [16]:
# np.insert(matrix, object or position, values, axis)

np.insert(a, 2, 20, 0)

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [20, 20, 20, 20],
        [ 9, 10, 11, 12]])

#### Inserting a new Matrix

In [20]:
col_new = np.matrix("20, 21, 22")
col_new

matrix([[20, 21, 22]])

In [23]:
row_new = np.matrix('30, 31, 32, 33')
row_new

matrix([[30, 31, 32, 33]])

In [21]:
#adding column wise
np.insert(a, 0, col_new, axis = 1)

matrix([[20,  1,  2,  3,  4],
        [21,  5,  6,  7,  8],
        [22,  9, 10, 11, 12]])

In [24]:
#adding row wise
np.insert(a, 0, row_new, 0)

matrix([[30, 31, 32, 33],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

### Updating a Matrix

In [26]:
b = np.insert(a, 0, row_new, 0)
b

matrix([[30, 31, 32, 33],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [27]:
#Replacing element [1, 1] position
b[1, 1] = 100
b

matrix([[ 30,  31,  32,  33],
        [  1, 100,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]])

In [29]:
# Accessing Elements of a Matrix using Index
b

matrix([[ 30,  31,  32,  33],
        [  1, 100,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]])

In [31]:
# Index row 1 and 2 columns
print(b[1, :2])

[[  1 100]]


In [32]:
# Extract 2nd row elements
print(b[2, :])

[[5 6 7 8]]


In [33]:
#Extract 3rd column
print(b[:, 2])

[[32]
 [ 3]
 [ 7]
 [11]]


## Matrix Operations

### Martix Addition

In [40]:
# Create two matrices A and B

A = np.matrix(np.arange(0, 20).reshape(5, 4))
A

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [43]:
B = np.matrix('50, 51, 52, 53; 54, 55, 56, 57;, 58, 59, 60, 61; 62, 63, 64, 65;, 66, 67, 68, 69')
B


matrix([[50, 51, 52, 53],
        [54, 55, 56, 57],
        [58, 59, 60, 61],
        [62, 63, 64, 65],
        [66, 67, 68, 69]])

In [45]:
np.add(A, B)

matrix([[50, 52, 54, 56],
        [58, 60, 62, 64],
        [66, 68, 70, 72],
        [74, 76, 78, 80],
        [82, 84, 86, 88]])

### Substraction

In [47]:
np.subtract(B, A)

matrix([[50, 50, 50, 50],
        [50, 50, 50, 50],
        [50, 50, 50, 50],
        [50, 50, 50, 50],
        [50, 50, 50, 50]])

### Matrix Multiplication

In [50]:
B = np.transpose(B) # or B = B.T

In [51]:
np.dot(A, B)

matrix([[ 314,  338,  362,  386,  410],
        [1138, 1226, 1314, 1402, 1490],
        [1962, 2114, 2266, 2418, 2570],
        [2786, 3002, 3218, 3434, 3650],
        [3610, 3890, 4170, 4450, 4730]])

### Elementwise Multiplication

In [52]:
A

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [53]:
B = np.matrix('50, 51, 52, 53; 54, 55, 56, 57;, 58, 59, 60, 61; 62, 63, 64, 65;, 66, 67, 68, 69')
B

matrix([[50, 51, 52, 53],
        [54, 55, 56, 57],
        [58, 59, 60, 61],
        [62, 63, 64, 65],
        [66, 67, 68, 69]])

In [54]:
np.multiply(A, B)

matrix([[   0,   51,  104,  159],
        [ 216,  275,  336,  399],
        [ 464,  531,  600,  671],
        [ 744,  819,  896,  975],
        [1056, 1139, 1224, 1311]])

### Division - Elementwise

In [55]:
np.divide(A, B)

matrix([[0.        , 0.01960784, 0.03846154, 0.05660377],
        [0.07407407, 0.09090909, 0.10714286, 0.12280702],
        [0.13793103, 0.15254237, 0.16666667, 0.18032787],
        [0.19354839, 0.20634921, 0.21875   , 0.23076923],
        [0.24242424, 0.25373134, 0.26470588, 0.27536232]])