# Linear Algebra

### Linear Algebra Operations in Python

**Determinant of a Matrix**

**Rank of Matrix**

**Inverse of a Matrix**

**Solving System of Equations**

In [2]:
import numpy as np

### Determinant

In [3]:
# Determinant of Matrix can be found for a Square Matrix
# Daterminant = ad - bc

x = np.matrix('4, 15, 16, 7; 2, -2, 3, -3; 3, 4, 5, 6; 4, 7, 8, 9')
x

matrix([[ 4, 15, 16,  7],
        [ 2, -2,  3, -3],
        [ 3,  4,  5,  6],
        [ 4,  7,  8,  9]])

In [5]:
det_matrix = np.linalg.det(x)
det_matrix

81.99999999999966

### Rank of a Matrix

In [6]:
np.linalg.matrix_rank(x)

4

In [7]:
# It(Rank) means it has four Linearly independent rows

### Inverse of a Matrix

In [9]:
# It return the multiplicative inverse of a matrix

np.linalg.inv(x)

matrix([[ 0.40243902, -0.36585366,  5.58536585, -4.15853659],
        [ 0.32926829, -0.3902439 ,  3.02439024, -2.40243902],
        [-0.25609756,  0.41463415, -3.46341463,  2.64634146],
        [-0.20731707,  0.09756098, -1.75609756,  1.47560976]])

In [11]:
# Another Example

mymatrix = np.matrix('2, 1, 2; 1, 0, 1;, 3, 1, 3')
mymatrix


matrix([[2, 1, 2],
        [1, 0, 1],
        [3, 1, 3]])

In [12]:
np.linalg.inv(mymatrix)

LinAlgError: Singular matrix

In [14]:
# For Singular Matrix determinant = 0

np.linalg.det(mymatrix)

0.0

In [15]:
# so condition to find inverse of a matrix is Determinant should not be zero


### System of Linear Equations

In [17]:
A= np.matrix('3, 1, 2; 3, 2, 5; 6, 7, 8')
A

matrix([[3, 1, 2],
        [3, 2, 5],
        [6, 7, 8]])

In [19]:
B = np.matrix('2; -1; 3')        # or np.matrix('2, -1, 3').transopse()
B

matrix([[ 2],
        [-1],
        [ 3]])

In [20]:
# Direct Method

np.linalg.solve(A, B)

matrix([[ 1.24242424],
        [ 0.81818182],
        [-1.27272727]])